### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by Madis0** [madiote/praktika#15]
The website may either be displayed on a separate domain (like [the virtual tour](http://virtuaaltuur.tlu.ee/)) or from the TLU domain (like [Astra/Silva building map](https://www.tlu.ee/silva-ja-astra-majaplaan)). 

The first would likely be easier to do as it only needs publishing, not coordination to work well with current website elements.

**Comment by madiote** [comment]
https://minitorn.cs.tlu.ee/dtimap/
